---
- name: user module demo
  hosts: appservers
  become: true
  tasks:
    - name: Create wheel group
      group:
        name: wheel
        state: present
    - name: Create adm group
      group:
        name: adm
        state: present
    - name: user example present
      ansible.builtin.user:
        name: example
        password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
        groups:
          - wheel
          - adm
        state: "present"
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/example"
        comment: "Ansible example"
        generate_ssh_key: true

